server:
  port: 8086

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/PullaguraHeptagon/config-server-git.git
          username: lakshmidevi.pullagura@gmail.com
          password: balapulla1
